import { GameStore } from '../src/state/store';
import { createSaveGame, serialize, deserialize } from '../src/state/save';
import { createStartingRun } from '../src/systems/setup';
import { chooseIdentity, goHome } from '../src/systems/phases';
import { createOrganizeSession, takeFromBox, householdTotals } from '../src/systems/organize';

const noop = { schedule() {}, flush() {}, dispose() {}, pending: false };
const store = new GameStore(createSaveGame(null), noop);
store.replaceRun(createStartingRun(1001));
console.log('phase:', store.run.phase, 'boxes:', store.run.boxesToUnpack.length);
chooseIdentity(store, 'porter');
console.log('after chooseIdentity phase:', store.run.phase);
goHome(store);
console.log('after goHome phase:', store.run.phase, 'boxes:', store.run.boxesToUnpack.length, 'box0 items:', store.run.boxesToUnpack[0]?.items?.length);
const session = createOrganizeSession();
const before = householdTotals(store.run).pieces;
const res = takeFromBox(store, session, store.run.boxesToUnpack[0].id);
console.log('takeFromBox ok:', res.ok, 'held:', session.held ? session.held.itemId : null, 'events:', JSON.stringify(res.events));
console.log('before:', before, '| in-memory after take:', householdTotals(store.run).pieces);
const loaded = deserialize(serialize(store.save));
console.log('after reload:', householdTotals(loaded.run).pieces);
